my_tuple=(1,3,4,5,6,7)
a=list(my_tuple)
print(a)
b=len(a)
print(b)
add_=a.append(8)
print(add_)
c=a.pop()
print(c )
a.remove(3)
print(my_tuple)

a=(2,3,4,5,67,5,4,34,15,4,)
b=int(input("enter a number:"))
c=a.count(b)
print(c)